ribbon.eureka.enabled: false

zuul:
  sensitive-headers:
  routes:
    #
    # RECORDER
    #

    # Artist
    rec_artists:
      path: /api/v1/artists
      url: ${REC_URL}
    # Playback
    rec_playbacks_mine:
      path: /api/v1/playbacks/mine
      url: ${REC_URL}
    rec_playbacks:
      path: /api/v1/playbacks/**
      url: ${REC_URL}/api/v1/playbacks/

    #
    # MBS
    #

    # Artist
    mbs_artists:
      path: /mbs/v1/artists/**
      url: ${MBS_URL}/mbs/v1/artists
    # Release Group
    mbs_releasegroups:
      path: /mbs/v1/releasegroups/**
      url: ${MBS_URL}/mbs/v1/releasegroups
    mbs_playbacks:
      path: /mbs/v1/playbacks/identify
      url: ${MBS_URL}
    # Recording
    mbs_recordings:
      path: /mbs/v1/recordings/**
      url: ${MBS_URL}/mbs/v1/recordings
